# Generated by Django 5.2.7 on 2025-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='transcribed_text',
            field=models.TextField(blank=True),
        ),
    ]
