# Generated by Django 5.2.8 on 2026-01-01 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0018_comment_expires_at'),
        ('transcriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='stt.audiofile'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcribed_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcription_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='transcription',
            constraint=models.UniqueConstraint(fields=('audio', 'user'), name='unique_audio_user_transcription'),
        ),
    ]
