# Generated by Django 5.2.7 on 2025-10-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0006_remove_audiofile_transcribed_text'),
        ('transcriptions', '0002_transcription_transcribed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='text',
        ),
        migrations.AlterField(
            model_name='transcription',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='stt.audiofile'),
        ),
    ]
