# Generated by Django 5.2.8 on 2026-01-01 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0018_comment_expires_at'),
        ('transcriptions', '0002_transcription_updated_at_alter_transcription_audio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transcription',
            name='unique_audio_user_transcription',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='transcripted',
        ),
        migrations.AlterField(
            model_name='transcription',
            name='audio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='stt.audiofile'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcribed_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
