# Generated by Django 5.2.7 on 2025-10-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0003_remove_transcription_text_alter_transcription_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='transcripted',
            field=models.BooleanField(default=False),
        ),
    ]
