# Generated by Django 5.2.8 on 2026-01-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0003_remove_transcription_unique_audio_user_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='transcripted',
            field=models.BooleanField(default=False),
        ),
    ]
