# Generated by Django 5.2.7 on 2025-10-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0004_transcription_transcripted'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='transcription_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
