# Generated by Django 5.2.7 on 2025-10-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0005_transcription_transcription_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='transcription_title',
            new_name='transcription_tag',
        ),
    ]
