# Generated by Django 5.2.8 on 2025-12-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio/')),
                ('audio_ganre', models.CharField(choices=[('lesson', 'Lesson'), ('lecture', 'Lecture'), ('podcust', 'Podcust')], default='lesson', max_length=20)),
                ('file_title', models.CharField(default='undefined', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done')], default='pending', max_length=20)),
                ('waveform_file', models.FileField(blank=True, null=True, upload_to='waveforms/')),
                ('transcripted', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment_status', models.CharField(choices=[('Not started', 'not started'), ('In progress', 'in progress'), ('Done', 'done')], default='Not started', max_length=20)),
                ('comment_type', models.CharField(choices=[('idea', 'Idea'), ('issue', 'Issue'), ('edit', 'Edit'), ('note', 'Note'), ('task', 'Task')], default='idea', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stt.audiofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
