# Generated by Django 5.2.1 on 2025-09-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='transcribed_text',
            field=models.TextField(blank=True),
        ),
    ]
