# Generated by Django 5.2.1 on 2025-09-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0002_audiofile_transcribed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='transcribed_text',
        ),
    ]
