# Generated by Django 5.2.1 on 2025-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0003_remove_audiofile_transcribed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='audio_ganre',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('lecture', 'Lecture'), ('podcust', 'Podcust')], default='lesson', max_length=20),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='file_title',
            field=models.CharField(default='undefined', max_length=50),
        ),
    ]
