# Generated by Django 5.2.1 on 2025-09-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0004_audiofile_audio_ganre_audiofile_file_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='transcribed_text',
            field=models.TextField(blank=True),
        ),
    ]
