# Generated by Django 5.2.7 on 2025-10-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0005_audiofile_transcribed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='transcribed_text',
        ),
    ]
