# Generated by Django 5.2.7 on 2025-10-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0006_remove_audiofile_transcribed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='transcripted',
            field=models.BooleanField(default=False),
        ),
    ]
