# Generated by Django 5.2.7 on 2025-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0007_audiofile_transcripted'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
