# Generated by Django 5.2.7 on 2025-11-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stt.audiofile'),
        ),
    ]
