# Generated by Django 5.2.7 on 2025-11-28 15:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0010_comment_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='waveform_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
