# Generated by Django 5.2.7 on 2025-11-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0011_audiofile_waveform_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='waveform_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
