# Generated by Django 5.2.8 on 2025-11-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0012_alter_audiofile_waveform_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='waveform_data',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='waveform_file',
            field=models.FileField(blank=True, null=True, upload_to='waveforms/'),
        ),
    ]
