# Generated by Django 5.2.8 on 2025-12-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0013_remove_audiofile_waveform_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
