# Generated by Django 5.2.8 on 2025-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0014_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('issue', 'Issue'), ('edit', 'Edit'), ('note', 'Note'), ('task', 'Task')], default='idea', max_length=20),
        ),
    ]
