# Generated by Django 5.2.8 on 2025-12-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0015_remove_comment_timestamp_comment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='status',
            new_name='comment_type',
        ),
    ]
