# Generated by Django 5.2.8 on 2025-12-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0016_rename_status_comment_comment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_status',
            field=models.CharField(choices=[('Not started', 'not started'), ('In progress', 'in progress'), ('Done', 'done')], default='Not started', max_length=20),
        ),
    ]
