# Generated by Django 5.2.8 on 2025-12-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0017_comment_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
