# Generated by Django 5.2.1 on 2025-09-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_completeduserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeduserprofile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completeduserprofile',
            name='profile_status',
            field=models.CharField(choices=[('active', 'Active'), ('away', 'Away'), ('offline', 'Offline')], default='lesson', max_length=20),
        ),
    ]
