# Generated by Django 5.2.7 on 2025-10-31 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0006_rename_transcription_title_transcription_transcription_tag'),
        ('users', '0005_chatmessage_transcripted_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='transcripted_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='transcriptions.transcription'),
        ),
    ]
